---
title: "Importação de dados"
author: "Análise de dados com linguagem R"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dadosHerica <- read.csv("Herika/Base_dados_Trabalho_Final.csv",sep = ";")
summary(dadosHerica)
```

```{r}
require(openxlsx)
dadosJulio <- read.xlsx("Julio/INGESTÃO DE ALCOOL.xlsx" , detectDates = TRUE) 
head(dadosJulio)
str(dadosJulio$km)

dadosJulio$km <- as.numeric( gsub("," , "." , dadosJulio$km ) )
```

Utilizando o argumento sheet = 2, deixamos indicado que iremos ler a tabela que está na segunda planilha do documento.
```{r}
require(readxl)
dadosMarony <- read_excel("Marony/EQ_10_anos_v2.xls",sheet = 2)
head(dadosMarony)
```


```{r}
dadosPedro <- read.csv("Pedro/saques_amostra_201701.csv",sep=";",encoding = "latin1")
head(dadosPedro)

str(dadosPedro$Valor.Parcela)
```

A coluna "Valor.Parcela" esta utilizando separador de virgula para milhares e de ponto para decimais. Portanto, nao foi lida corretamente. Vamos retirar as virgulas referente aos milhares, e transformar em um vetor numérico.
```{r}
dadosPedro$Valor.Parcela <- as.numeric( gsub("," , "" , dadosPedro$Valor.Parcela))

str(dadosPedro$Valor.Parcela)
```


```{r}
require(openxlsx)
dadosFernando <- read.xlsx("fernando/Planilha PNAE AF 2016.xlsx",startRow = 9)
head(dadosFernando)
summary(dadosFernando)
```

